### ISSUE TITLE
Random starts are too punishing

### ISSUE THREAD

**Issue by tinyhoot** [tinyhoot/SubnauticaRandomiser#40]
Using the Random setting for random starts is highly likely to start you off in a biome where the ground is 200m below you. Perhaps preserve this setting, but also include one that only considers decent starting biomes with depth < 100m?

**Comment by jet082** [comment]
If I can make a request for this - it might be nice to ensure that the balanced/limited version is an option (and probably the default), but the more remote biome spawns are still available if you want them.

Random Start and Expanded Random Start might be nice options or something like that.

**Comment by jet082** [comment]
(To that end - and possibly longer term - it might be nice to even have deeper biomes as random starting locations, provided relevant equipment is buildable from local materials. For example, starting in the Lost River or Jellyshroom Caves, but having the rebreather and relevant tanks buildable via nickel or crystalline sulfur. It would be neat to be able to have 'going up' be progression rather than 'going down' like in the typical game)

**Comment by tinyhoot** [comment]
> If I can make a request for this - it might be nice to ensure that the balanced/limited version is an option (and probably the default), but the more remote biome spawns are still available if you want them.

That's pretty much what I had in mind. Much like right now every biome is selectable individually beyond the current Random setting, I think renaming the current one and simply adding a limited variant as the default would be the best and most customisable way.

Long term, it might be nice to have a way to start on the ground floor, rather than always floating on top. That would tie nicely into your "building up" idea, which sounds really interesting!

**Comment by RayRobertson72** [comment]
> > If I can make a request for this - it might be nice to ensure that the balanced/limited version is an option (and probably the default), but the more remote biome spawns are still available if you want them.
> 
> That's pretty much what I had in mind. Much like right now every biome is selectable individually beyond the current Random setting, I think renaming the current one and simply adding a limited variant as the default would be the best and most customisable way.
> 
> Long term, it might be nice to have a way to start on the ground floor, rather than always floating on top. That would tie nicely into your "building up" idea, which sounds really interesting!

I have been starting at the bottom with the Deathrun mod(it sinks you to the bottom) while also having Randomiser Remade's Chaotic Random location active randomised recipes active at default settings.

One tends to still have to swim to the safe shallows to get ingredients for the starting tools and equipment.

If and when you add this, I suggest the logic rather use resources you can find in the biome you spawn in rather than using depth for ingredients of starting tools and equipment.

I'm really enjoying your work.
