### ISSUE TITLE
Question regarding starting location

### ISSUE THREAD

**Issue by RayRobertson72** [tinyhoot/SubnauticaRandomiser#51]
Hi. Enjoying this mod. Use Accelerated Start mod to give myself a little bit of a fighting chance. Starting with a Scanner, Standard o2 tank, survival knife, rebreather and Stasis rifle. Been playing with Chaotic Random location.

What is the difference between random and chaotic random starting locations?

**Comment by tinyhoot** [comment]
Personally I'd recommend dropping the knife from that list if you play with seeds enabled, since that can really cut some corners in the logic, but you do whatever you enjoy.

The difference between random and chaotic random is that random is constrained to somewhat favourable starting biomes where you won't have to swim _too_ far. It won't drop you over 350m of open water. Iirc it only considers biomes that have a ground level at ~150m or so.
Chaotic random on the other hand chooses from _any_ of the available options, including the Void.

**Comment by RayRobertson72** [comment]
> 

Thanks for your reply. I’m rather enjoying the deep water starts also, it why I add the rebreather. Is there an easy edit I could do in the alternateStart.csv file that would exclude the void?

**Comment by tinyhoot** [comment]
I think so, yes. The last element in the alternateStarts.csv, the [line marked as "None"](https://github.com/tinyhoot/SubnauticaRandomiser/blob/e41e0fc3dfec2405cc028678f0ceca21fb2aa8f6/DataFiles/alternateStarts.csv#L16), is the one that defines Void spawns. If you simply remove that line Chaotic Random should give you anything excluding the void.

There's a possibility that this change could make the randomiser crash, especially if you specifically select Void as your starting biome (but why would you?). But if it happens at all, it will be as soon as you press the button to apply your changes. If you get past that point with no complaints, you're all set.

**Comment by RayRobertson72** [comment]
> I think so, yes. The last element in the alternateStarts.csv, the [line marked as "None"](https://github.com/tinyhoot/SubnauticaRandomiser/blob/e41e0fc3dfec2405cc028678f0ceca21fb2aa8f6/DataFiles/alternateStarts.csv#L16), is the one that defines Void spawns. If you simply remove that line Chaotic Random should give you anything excluding the void.
> 
> There's a possibility that this change could make the randomiser crash, especially if you specifically select Void as your starting biome (but why would you?). But if it happens at all, it will be as soon as you press the button to apply your changes. If you get past that point with no complaints, you're all set.

Thanks a lot. Seems to be working.
